name: "redpanda-action"
description: "Setup Redpanda"
author: "fernandes"
branding:
  icon: fast-forward
  color: red
inputs:
  version:
    description: "Version of Redpanda to use"
    required: false
    default: "latest"
  hostname:
    description: "Hostname of the Container"
    required: false
    default: "redpanda"
runs:
  using: "docker"
  image: "Dockerfile"
