name: "redpanda-action"
description: "Setup Redpanda"
author: "fernandes"
branding:
  icon: fast-forward
  color: red
inputs:
  version:
    description: "Version of Redpanda Kafka to use"
    required: false
    default: "latest"
runs:
  using: "docker"
  image: "Dockerfile"
